### ISSUE TITLE
Support Universal Links for "Go To Link" button action

### ISSUE THREAD

**Issue by GermanVelibekovHouzz** [appcues/appcues-ios-sdk#277]
We set a universal link to the app opening an Appcues campaign here:
![image](https://user-images.githubusercontent.com/81903043/199924498-9cb1494a-0f30-4f0b-9d14-9a76f79a004e.png)
We expect a user to stay within the app once he taps this button and link to be handled as a deeplink bringing the user to the relevant experience.
The actual result: the external browser is opened

I believe this is due to how the method you use to open links [works](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html):
![image](https://user-images.githubusercontent.com/81903043/199926979-d0da255d-8e5a-4755-bc1e-36ec3314b25b.png)

Can you please support the universal links so the above scenario will be handled? 
Possible solutions are:
- [using alternative opening methods](https://stackoverflow.com/questions/46834222/how-can-i-use-universal-links-when-i-call-openurl-inside-my-own-app)
- adding a new "Open in the app" configuration and use [this option](https://developer.apple.com/documentation/uikit/uiapplication/openexternalurloptionskey/1648680-universallinksonly) to open such urls.

> Note: I know that today we're able to achieve the desired result using the [app url scheme](https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app). However, we prefer not to do so as it carries potential risks, makes campaigns iOS specific and creates unnecessary conventions.

Thank you!

**Comment by iujames** [comment]
Hi @GermanVelibekovHouzz - thank you for the feedback and excellent details in the request! This sounds like a valid use case that we would want to enable, and we're looking over the options you noted to see what we can make work. We will follow up soon with findings here. Thanks!

**Comment by mmaatttt** [comment]
Hi @GermanVelibekovHouzz, we've just released a new version of the SDK, `1.1.0` that supports universal links.

We adopted the first possible solution you proposed, so the details hopefully are familiar to you, but we've also put together a brief document explaining how the SDK supports universal links: https://appcues.github.io/appcues-ios-sdk/documentation/appcueskit/universallinking

**Comment by GermanVelibekovHouzz** [comment]
Hey @mmaatttt. This is awesome! 👏. Thank you for your quick response to the issue. What you did guys will help us a lot. 🙏
